// Bootstrap: expose the handlers used by inline onclick attributes, wire up
// DOM listeners, and restore any saved itinerary. This is the bundle entry
// point (scripts/build.mjs inlines the bundle into the built HTML).
import { state, H_SCHEMA_VERSION } from './state.js';
import { load, loadUpload, uploadAnyway, uploadCancel, importReplace, importBoth, importCancel, closeTrip, switchView, tabKey, download, toggleEdit, openEdit, openEditTrip, openAddSegment, openNewItinerary, openEditList, openAddList, openEditPhraseGroup, openAddPhraseGroup, openEditPhrase, closeEdit, saveEdit, editTab, deleteEdit, downloadSaved, forceLoadSaved, discardSaved } from './app.js';
import { libOpen, libClose, libSwitch, libRevs, libDelete, libRestore, libDownloadRev, libSaveName, libForgetAll } from './views/library.js';
import { boot, shareTrip, shareRevision, shareToastClose } from './share.js';
import { dismissStoreWarning } from './store.js';
import { toggleGanttMode } from './views/gantt.js';
import { jumpToDay } from './views/list.js';
import { toggleListItem, revealListSegment, addListItem, addListItemKey, deleteListItem, undoDeleteListItem, scheduleListItem, editListItem, jumpToList } from './views/lists.js';
import { addPhrase, addPhraseKey, deletePhrase, undoDeletePhrase, jumpToPhraseGroup } from './views/phrases.js';
import { chatOpen, chatClose, chatClear, chatSubmit, renderChat, syncChatViewport } from './ai/chat.js';
import { discardDraft, applyDraft } from './ai/preview.js';
import { settingsOpen, settingsClose, settingsSave, settingsClearKey } from './ai/settings.js';
import { initServiceWorker } from './sw-register.js';
import { setupValidation } from './validate.js';

window.H_SCHEMA_VERSION = H_SCHEMA_VERSION;

// ajv and the schema are compiled into this bundle, so the validators exist
// before anything can load a document — including a share link in the
// fragment, which boot() reads below.
setupValidation();

// Handlers referenced from inline onclick attributes (static markup and
// markup generated by the views) must be reachable as window globals.
Object.assign(window, {
  hload: load,
  hCloseTrip: closeTrip,
  hLibOpen: libOpen,
  hLibClose: libClose,
  hLibSwitch: libSwitch,
  hLibRevs: libRevs,
  hLibDelete: libDelete,
  hLibRestore: libRestore,
  hLibDownloadRev: libDownloadRev,
  hLibShareRev: shareRevision,
  hLibSaveName: libSaveName,
  hLibForget: libForgetAll,
  hStoreWarnClose: dismissStoreWarning,
  hsw: switchView,
  hDownload: download,
  hShare: shareTrip,
  hShareToastClose: shareToastClose,
  hToggleEdit: toggleEdit,
  hOpenEdit: openEdit,
  hOpenEditTrip: openEditTrip,
  hAddSegment: openAddSegment,
  hNewItinerary: openNewItinerary,
  hCloseEdit: closeEdit,
  hSaveEdit: saveEdit,
  hEditTab: editTab,
  hDeleteEdit: deleteEdit,
  hGanttToggle: toggleGanttMode,
  hJumpDay: jumpToDay,
  hListToggle: toggleListItem,
  hListSchedule: scheduleListItem,
  hListSeg: revealListSegment,
  hListAdd: addListItem,
  hListAddKey: addListItemKey,
  hListDel: deleteListItem,
  hListUndo: undoDeleteListItem,
  hJumpList: jumpToList,
  hOpenEditList: openEditList,
  hOpenAddList: openAddList,
  hOpenEditListItem: editListItem,
  hPhraseAdd: addPhrase,
  hPhraseAddKey: addPhraseKey,
  hPhraseDel: deletePhrase,
  hPhraseUndo: undoDeletePhrase,
  hJumpPhraseGroup: jumpToPhraseGroup,
  hOpenEditPhraseGroup: openEditPhraseGroup,
  hOpenAddPhraseGroup: openAddPhraseGroup,
  hOpenEditPhrase: openEditPhrase,
  hUploadAnyway: uploadAnyway,
  hUploadCancel: uploadCancel,
  hImportReplace: importReplace,
  hImportBoth: importBoth,
  hImportCancel: importCancel,
  hDownloadSaved: downloadSaved,
  hForceLoadSaved: forceLoadSaved,
  hDiscardSaved: discardSaved,
  hChatOpen: chatOpen,
  hChatClose: chatClose,
  hChatClear: chatClear,
  hChatSubmit: chatSubmit,
  hDiscardDraft: discardDraft,
  hApplyDraft: applyDraft,
  hSetOpen: settingsOpen,
  hSetClose: settingsClose,
  hSetSave: settingsSave,
  hSetClearKey: settingsClearKey,
});

/* file picker + drag-and-drop upload */
function loadFile(f) {
  if (!f) return;
  const r = new FileReader();
  r.onload = ev => { try { loadUpload(ev.target.result); } catch (err) { alert('Invalid JSON: ' + err.message); } };
  r.readAsText(f);
}
document.getElementById('hfile').addEventListener('change', e => {
  loadFile(e.target.files[0]); e.target.value = '';
});
const dz = document.getElementById('hdz');
dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('over'); });
dz.addEventListener('dragleave', () => dz.classList.remove('over'));
dz.addEventListener('drop', e => {
  e.preventDefault(); dz.classList.remove('over');
  loadFile(e.dataTransfer.files[0]);
});

/* Tab strip: Left/Right/Home/End move along it (issue #90). One listener on the
   tablist rather than an inline onkeydown per tab — the tabs' onclick already
   carries the activation, and this is the only key handling they need. */
document.querySelector('.htabs').addEventListener('keydown', tabKey);

/* chat input UX: Enter to send, Shift+Enter for newline, auto-grow */
{
  const ta = document.getElementById('hchat-input');
  ta.addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSubmit(); } });
  ta.addEventListener('input', () => { ta.style.height = 'auto'; ta.style.height = Math.min(ta.scrollHeight, 120) + 'px'; });
}

/* keep the fixed chat panel matched to the visual viewport (mobile URL bar +
   on-screen keyboard) — see syncChatViewport in ai/chat.js (issue #25) */
if (window.visualViewport) {
  window.visualViewport.addEventListener('resize', syncChatViewport);
  window.visualViewport.addEventListener('scroll', syncChatViewport);
}

renderChat();
// A #d1= share link takes precedence over the trip that was open; with no
// link, boot() is just loadSaved() (issue #81).
boot();
initServiceWorker();

export { state }; // handy for debugging from the console via the bundle
