// Bootstrap: expose the handlers used by inline onclick attributes, wire up
// DOM listeners, and restore any saved itinerary. This is the bundle entry
// point (scripts/build.mjs inlines the bundle into the built HTML).
import { state, H_SCHEMA_VERSION } from './state.js';
import { load, loadUpload, uploadAnyway, uploadCancel, reset, switchView, download, toggleEdit, openEdit, openEditTrip, openScheduleItem, closeEdit, saveEdit, deleteSegment, loadSaved, downloadSaved, forceLoadSaved, discardSaved } from './app.js';
import { toggleGanttMode } from './views/gantt.js';
import { jumpToDay } from './views/list.js';
import { toggleListItem, revealListSegment } from './views/lists.js';
import { chatOpen, chatClose, chatClear, chatSubmit, renderChat, syncChatViewport } from './ai/chat.js';
import { discardDraft, applyDraft } from './ai/preview.js';
import { settingsOpen, settingsClose, settingsSave, settingsClearKey } from './ai/settings.js';
import { initServiceWorker } from './sw-register.js';

// validate.js (a separate inline module script in the built page) compares
// this against the schema.version it fetches at runtime.
window.H_SCHEMA_VERSION = H_SCHEMA_VERSION;

// Handlers referenced from inline onclick attributes (static markup and
// markup generated by the views) must be reachable as window globals.
Object.assign(window, {
  hload: load,
  hreset: reset,
  hsw: switchView,
  hDownload: download,
  hToggleEdit: toggleEdit,
  hOpenEdit: openEdit,
  hOpenEditTrip: openEditTrip,
  hCloseEdit: closeEdit,
  hSaveEdit: saveEdit,
  hDeleteSegment: deleteSegment,
  hGanttToggle: toggleGanttMode,
  hJumpDay: jumpToDay,
  hListToggle: toggleListItem,
  hListSchedule: openScheduleItem,
  hListSeg: revealListSegment,
  hUploadAnyway: uploadAnyway,
  hUploadCancel: uploadCancel,
  hDownloadSaved: downloadSaved,
  hForceLoadSaved: forceLoadSaved,
  hDiscardSaved: discardSaved,
  hChatOpen: chatOpen,
  hChatClose: chatClose,
  hChatClear: chatClear,
  hChatSubmit: chatSubmit,
  hDiscardDraft: discardDraft,
  hApplyDraft: applyDraft,
  hSetOpen: settingsOpen,
  hSetClose: settingsClose,
  hSetSave: settingsSave,
  hSetClearKey: settingsClearKey,
});

/* file picker + drag-and-drop upload */
function loadFile(f) {
  if (!f) return;
  const r = new FileReader();
  r.onload = ev => { try { loadUpload(ev.target.result); } catch (err) { alert('Invalid JSON: ' + err.message); } };
  r.readAsText(f);
}
document.getElementById('hfile').addEventListener('change', e => {
  loadFile(e.target.files[0]); e.target.value = '';
});
const dz = document.getElementById('hdz');
dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('over'); });
dz.addEventListener('dragleave', () => dz.classList.remove('over'));
dz.addEventListener('drop', e => {
  e.preventDefault(); dz.classList.remove('over');
  loadFile(e.dataTransfer.files[0]);
});

/* chat input UX: auto-grow, plus Enter-to-send only where a physical keyboard
   makes Shift+Enter easy. On touch devices (coarse pointer) Enter inserts a
   newline like any other field so multi-line messages can be composed on
   mobile — the Send button is the only way to submit there. */
{
  const ta = document.getElementById('hchat-input');
  const enterSends = !(window.matchMedia && window.matchMedia('(pointer: coarse)').matches);
  if (enterSends)
    ta.addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSubmit(); } });
  ta.addEventListener('input', () => { ta.style.height = 'auto'; ta.style.height = Math.min(ta.scrollHeight, 160) + 'px'; });
}

/* keep the fixed chat panel matched to the visual viewport (mobile URL bar +
   on-screen keyboard) — see syncChatViewport in ai/chat.js (issue #25) */
if (window.visualViewport) {
  window.visualViewport.addEventListener('resize', syncChatViewport);
  window.visualViewport.addEventListener('scroll', syncChatViewport);
}

renderChat();
loadSaved();
initServiceWorker();

export { state }; // handy for debugging from the console via the bundle
